DROP TABLE personal_medico IF EXISTS;
DROP TABLE establecimiento IF EXISTS;
DROP TABLE region IF EXISTS;
DROP TABLE seremi IF EXISTS;
DROP TABLE paciente IF EXISTS;
DROP TABLE estado IF EXISTS;
DROP TABLE antecedente IF EXISTS;
DROP TABLE caso IF EXISTS;
CREATE TABLE personal_medico (
  med_run       int GENERATED BY DEFAULT AS IDENTITY, 
  med_nombres   varchar(255) NOT NULL, 
  med_apellidos varchar(255) NOT NULL, 
  med_telefono  varchar(255) NOT NULL, 
  med_email     varchar(255) NOT NULL, 
  PRIMARY KEY (med_run));
CREATE TABLE establecimiento (
  est_id        int GENERATED BY DEFAULT AS IDENTITY, 
  est_nombre    varchar(255) NOT NULL, 
  est_direccion varchar(255), 
  reg_id        int NOT NULL, 
  PRIMARY KEY (est_id));
CREATE TABLE region (
  reg_id     int GENERATED BY DEFAULT AS IDENTITY, 
  reg_nombre varchar(255) NOT NULL, 
  PRIMARY KEY (reg_id));
CREATE TABLE seremi (
  ser_id     int GENERATED BY DEFAULT AS IDENTITY, 
  ser_nombre varchar(255) NOT NULL, 
  reg_id     int NOT NULL, 
  PRIMARY KEY (ser_id));
CREATE TABLE paciente (
  pac_run                 int GENERATED BY DEFAULT AS IDENTITY, 
  pac_nombres             varchar(255) NOT NULL, 
  pac_apellidos           varchar(255) NOT NULL, 
  pac_sexo                varchar(255) NOT NULL, 
  pac_fecha_nacimiento    varchar(255) NOT NULL, 
  pac_fecha_fallecimiento varchar(255), 
  pac_nacionalidad        varchar(255) NOT NULL, 
  pac_pueblo_originario   varchar(255) NOT NULL, 
  pac_direccion           varchar(255) NOT NULL, 
  pac_telefono            int NOT NULL, 
  pac_comuna_residencia   varchar(255) NOT NULL, 
  pac_region_residencia   varchar(255) NOT NULL, 
  est_id                  int NOT NULL, 
  med_run                 int NOT NULL, 
  etd_id                  int NOT NULL, 
  PRIMARY KEY (pac_run));
CREATE TABLE estado (
  etd_id     int GENERATED BY DEFAULT AS IDENTITY, 
  etd_nombre int NOT NULL, 
  PRIMARY KEY (etd_id));
CREATE TABLE antecedente (
  ant_id                  int GENERATED BY DEFAULT AS IDENTITY, 
  ant_embarazo            tinyint, 
  ant_semana_gestacion    int NOT NULL, 
  ant_enfermedad_cronica  varchar(255), 
  ant_alergias            varchar(255) NOT NULL, 
  ant_tipo_sangre         varchar(255), 
  ant_medicamentos        varchar(255) NOT NULL, 
  ant_viaje_al_extranjero varchar(255), 
  pac_run                 int NOT NULL, 
  PRIMARY KEY (ant_id));
CREATE TABLE caso (
  cas_id                      int GENERATED BY DEFAULT AS IDENTITY, 
  cas_fecha_notificacion      varchar(255) NOT NULL, 
  cas_asintomatico            tinyint NOT NULL, 
  cas_fecha_primeros_sintomas varchar(255) NOT NULL, 
  cas_semana_epidemiologica   int, 
  cas_razon_sospecha          varchar(255), 
  cas_sintomas                varchar(255) NOT NULL, 
  cas_clasificacion_final     varchar(255), 
  cas_hospitalizacion         tinyint, 
  pac_run                     int NOT NULL, 
  PRIMARY KEY (cas_id));
ALTER TABLE establecimiento ADD CONSTRAINT FKestablecim216998 FOREIGN KEY (reg_id) REFERENCES region (reg_id);
ALTER TABLE seremi ADD CONSTRAINT FKseremi719081 FOREIGN KEY (reg_id) REFERENCES region (reg_id);
ALTER TABLE paciente ADD CONSTRAINT FKpaciente535873 FOREIGN KEY (est_id) REFERENCES establecimiento (est_id);
ALTER TABLE paciente ADD CONSTRAINT FKpaciente914863 FOREIGN KEY (med_run) REFERENCES personal_medico (med_run);
ALTER TABLE paciente ADD CONSTRAINT FKpaciente7789 FOREIGN KEY (etd_id) REFERENCES estado (etd_id);
ALTER TABLE antecedente ADD CONSTRAINT FKantecedent470191 FOREIGN KEY (pac_run) REFERENCES paciente (pac_run);
ALTER TABLE caso ADD CONSTRAINT FKcaso614007 FOREIGN KEY (pac_run) REFERENCES paciente (pac_run);
